spring:
  # Failed to bind properties under '' to com.zaxxer.hikari.HikariDataSource: ???  datasource ??
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: ENC(8tolwLfQQQ9DPdrlKftzDg==)
    password: ENC(LkwenwLQXA0HpQeSSYYoww==)

    hikari:
      driver-class-name: org.mariadb.jdbc.Driver
      connection-init-sql: SELECT 1
      minimum-idle: 1
      idle-timeout: 300000
      maximum-pool-size: 31
      max-lifetime: 540000
      username: ENC(8tolwLfQQQ9DPdrlKftzDg==)
      password: ENC(LkwenwLQXA0HpQeSSYYoww==)


  datasource-batch:
    use: true
    url: ENC(Y4X/JjWLC0L4pc5vy776MRPdEbgXgVgzuLGFxGidZHmZ4VgUtHzzVF209Xtok0GWWgu2PtQHyioIAZGRU+nvyaf+299lxeC/plQ+8/6MTqa5tw+flc3XQInAuS6mZsGPYZNN+q6c/nHY+xfNI0/kbeequsCYWDd/)
  datasource-lotto:
    use: false
    url: ENC(9Uzrmtjv64kzbo+KDPtPWfPWN2rBzOKHX28J8aLFtPQ4hPypDPADqBKLQahAjwf8LYMa/bbXmKjeJb7A1IzJ4b+5YT3eWxcE2vk9Pa7D0iuZ6i09sFJwHdmlfDVWBTrJRUx/e9kMwzIflXDzJ5F7qVX7qJG5BwSe)

jasypt:
  encryptor:
    bean: jasyptStringEncryptor
    password: 
    algorithm: PBEWithMD5AndDES
    salt-generator-classname: org.jasypt.salt.RandomSaltGenerator
    string-output-type: base64
    pool-size: 1
    key-obtention-iterations: 1000